layout: sidebar
style: light

theme: jekyll-theme-primer

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

repository: kleisauke/kleisauke.github.io

repositories:
  - html_url: https://github.com/weserv/images
    name: weserv/images
    description: Source code of wsrv.nl (formerly images.weserv.nl), to be used on your own server(s).
    language: C++
    stargazers_count: 1.5k
    forks_count: 166
  - html_url: https://github.com/libvips/libvips
    name: libvips/libvips
    description: A fast image processing library with low memory needs.
    language: C
    stargazers_count: 8.7k
    forks_count: 642
  - html_url: https://github.com/kleisauke/net-vips
    name: net-vips
    description: .NET binding for libvips.
    language: C#
    stargazers_count: 355
    forks_count: 32
  - html_url: https://github.com/kleisauke/wasm-vips
    name: wasm-vips
    description: libvips for the browser and Node.js, compiled to WebAssembly with Emscripten.
    language: C++
    stargazers_count: 408
    forks_count: 22
  - html_url: https://github.com/lovell/sharp
    name: lovell/sharp
    description: High performance Node.js image processing, the fastest module to resize JPEG, PNG, WebP, AVIF and TIFF images. Uses the libvips library.
    language: JavaScript
    stargazers_count: 27k
    forks_count: 1.3k
  - html_url: https://github.com/libvips/ruby-vips
    name: libvips/ruby-vips
    description: Ruby extension for the libvips image processing library.
    language: Ruby
    stargazers_count: 804
    forks_count: 63

social_media:
  linkedin: kleisauke
  stackoverflow: 10952119
  website: https://kleisauke.nl

topics:
  - name: C
    web_url: https://github.com/topics/c
    image_url: https://raw.githubusercontent.com/github/explore/f3e22f0dca2be955676bc70d6214b95b13354ee8/topics/c/c.png
  - name: C++
    web_url: https://github.com/topics/cpp
    image_url: https://raw.githubusercontent.com/github/explore/180320cffc25f4ed1bbdfd33d4db3a66eeeeb358/topics/cpp/cpp.png
  - name: C#
    web_url: https://github.com/topics/csharp
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/csharp/csharp.png
  - name: Linux
    web_url: https://github.com/topics/linux
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/linux/linux.png
  - name: nginx
    web_url: https://github.com/topics/nginx
    image_url: https://raw.githubusercontent.com/github/explore/85cceaeeaf993ca35664dc37ea24f9237fbbfc14/topics/nginx/nginx.png
  - name: libvips
    web_url: https://github.com/topics/libvips

sass:
  style: compressed

compress_html:
  clippings: [html, head, body, link, meta, div, p, h1, h2, img, title, svg, a, span]
  comments: all
