title: Kleis Auke Wolthuizen
author:
  name: Kleis Auke Wolthuizen
  title:
    en: Application Developer
    nl: Applicatieontwikkelaar
meta:
  app-name: KleisAuke.nl
  description:
    en: Personal website of Kleis Auke Wolthuizen
    nl: Persoonlijke website van Kleis Auke Wolthuizen
  keywords:
    - Kleis Auke Wolthuizen
    - student
    - cv
    - vcard
    - html5
    - portfolio
    - info
menu:
  - title:
      en: About me
      nl: Over mij
    url:
      en: about
      nl: over
    id:
      en: "about"
      nl: "over"
  - title:
      en: Resume
      nl: In het kort
    url:
      en: resume
      nl: in-het-kort
    id:
      en: "resume"
      nl: "in-het-kort"
  - title: Portfolio
    url: portfolio
    id: "portfolio"
  - title:
      en: Contact
      nl: Contact
    url:
      en: contact
      nl: contact
    id:
      en: "contact"
      nl: "contact"
about:
  caption:
    en: ...an <span class="label primary">application developer</span>
    nl: ...een <span class="label primary">applicatieontwikkelaar</span>
  info:
    en: I'm Kleis Auke Wolthuizen, an application developer from Sneek. Since 2016, I study computer science at the NHL in Leeuwarden.
    nl: Ik ben Kleis Auke Wolthuizen, een applicatieontwikkelaar uit Sneek. Sinds 2016 volg ik de opleiding informatica aan de NHL in Leeuwarden.
  personal-info:
    - value: <a href="mailto:info@kleisauke.nl">info@kleisauke.nl</a>
      icon: fas fa-envelope
    - value: +31 (0)6 1226 7733
      icon: fas fa-phone
    - value:
        en: <a href="/vCard.vcf">Electronic business card</a>
        nl: <a href="/vCard.vcf">Elektronische visitekaartje</a>
      icon: fas fa-address-card
    - value: <a href="https://github.com/kleisauke">GitHub</a>
      icon: fab fa-github
    - value: <a href="https://www.linkedin.com/in/kleisauke/">LinkedIn</a>
      icon: fab fa-linkedin
  personal-info-caption:
    en: More information
    nl: Meer informatie
  github-activity-caption:
    en: My recent GitHub activity
    nl: Mijn recente GitHub activiteit
  pictures:
    - alt:
        en: Profile picture
        nl: Profielafbeelding
      cover: true
      src: assets/images/site/profile-1.jpg
    - alt:
        en: Profile picture
        nl: Profielafbeelding
      cover: false
      src: assets/images/site/profile-2.png
  social:
    - class: facebook
      icon: "&#88;"
      url: https://www.facebook.com/KleisAuke
    - class: google
      icon: "&#107;"
      url: https://plus.google.com/103295153955671980965/
resume:
  education:
    - degree:
        en: Bachelor degree
        nl: Bacheloropleiding
      duration:
        en: 2016 to present
        nl: 2016 tot heden
      major:
        en: Computer Science
        nl: Informatica
      organization:
        en: NHL University Leeuwarden
        nl: NHL Hogeschool Leeuwarden
    - degree:
        en: MBO (level 4)
        nl: MBO (niveau 4)
      duration:
        en: 2012 to 2016
        nl: 2012 tot 2016
      major:
        en: Maritime Engineering, Ship and Yacht Construction
        nl: Maritieme Techniek, Scheeps- en Jachtbouwkunde
      organization:
        en: ROC Friese Poort Sneek
        nl: ROC Friese Poort Sneek
    - degree:
        en: VMBO (middle management-oriented learning path)
        nl: VMBO (kaderberoepsgerichte leerweg)
      duration:
        en: 2007 to 2012
        nl: 2007 tot 2012
      major:
        en: Secondary education
        nl: Voortgezet onderwijs
      organization:
        en: Maritime Academy Harlingen
        nl: Maritieme Academie Harlingen
  education-title:
    en: Education
    nl: Opleidingen
  skills:
    - name: PHP
      percentage: 80
    - name: Java
      percentage: 70
    - name: C#
      percentage: 75
    - name: C++
      percentage: 60
    - name: HTML, CSS3, JavaScript
      percentage: 80
  skills-title:
    en: Development Skills
    nl: Vaardigheden
portfolio:
  filters:
    - current: true
      data-filter: "*"
      name:
        en: all
        nl: alles
    - current: false
      data-filter: .mobile
      name: app
    - current: false
      data-filter: .web
      name:
        en: website
        nl: website
    - current: false
      data-filter: .library
      name:
        en: library
        nl: bibliotheek
  items:
    - id: portfolio-item-01
    - id: portfolio-item-02
    - id: portfolio-item-03
    - id: portfolio-item-04
contact:
  email: E-mail
  email-label:
    en: So I can get back to you
    nl: Zodat ik je terug kan e-mailen
  email-post: https://kleisauke.nl/assets/php/send-mail.php
  email-title:
    en: Send me an email
    nl: Stuur mij een e-mail
  email-error:
    en: The email address you entered does not appear to be a valid address.
    nl: Het e-mailadres dat u hebt opgegeven lijkt niet een geldig adres te zijn.
  location:
    en: Where am I in this world?
    nl: Waar ben ik in deze wereld?
  map-src: https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d38393.16892691919!2d5.6720706!3d53.0280375!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47c8f1b7ff39f791%3A0x75235a11696bd87a!2sSneek!5e0!3m2!1snl!2snl!4v1442493564758
  message:
    en: Message
    nl: Bericht
  message-label:
    en: Enter your message...
    nl: Typ hier je bericht...
  message-error:
    en: The message you entered is too short. It must be at least 5 characters.
    nl: Het bericht die u hebt ingevoerd is te kort. Het moet minimaal 5 tekens lang zijn.
  name:
    en: Name
    nl: Naam
  name-label:
    en: What is your name?
    nl: Wat is je naam?
  resend-email:
    en: Send another email
    nl: Nog een e-mail sturen
  send-button:
    en: Send
    nl: Verzenden
  try-again:
    en: Try again
    nl: Probeer het nog eens
collections:
  - portfolio_collection
footer:
  language-chooser:
    en: Change your language
    nl: Wijzig je taal
  languages:
    - flag: flag-icon-nl
      name: Nederlands
      short: nl
    - flag: flag-icon-gb
      name: English
      short: en
main-language: nl
baseurl: ""

# the base hostname & protocol
url: "https://kleisauke.nl"

# Build settings
markdown: kramdown

sass:
  style: compressed

source: jekyll
destination: html
