layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

repository: kleisauke/kleisauke.github.io

# TODO: https://github.com/github/personal-website/issues/14
repositories:
  - html_url: https://github.com/weserv/images
    name: weserv/images
    description: Source code of images.weserv.nl, to be used on your own server(s).
    language: C++
    stargazers_count: 451
    forks_count: 42
  - html_url: https://github.com/libvips/libvips
    name: libvips/libvips
    description: A fast image processing library with low memory needs.
    language: C
    stargazers_count: 3.4k
    forks_count: 296
  - html_url: https://github.com/kleisauke/net-vips
    name: net-vips
    description: .NET binding for libvips
    language: C#
    stargazers_count: 78
    forks_count: 11
  - html_url: https://github.com/lovell/sharp
    name: lovell/sharp
    description: High performance Node.js image processing, the fastest module to resize JPEG, PNG, WebP and TIFF images. Uses the libvips library.
    language: JavaScript
    stargazers_count: 13.9k
    forks_count: 749
  - html_url: https://github.com/libvips/php-vips
    name: libvips/php-vips
    description: php binding for libvips
    language: PHP
    stargazers_count: 215
    forks_count: 9
  - html_url: https://github.com/libvips/ruby-vips
    name: libvips/ruby-vips
    description: Ruby extension for the libvips image processing library.
    language: Ruby
    stargazers_count: 528
    forks_count: 43

social_media:
  linkedin: kleisauke
  stackoverflow: 10952119
  website: https://kleisauke.nl

topics:
  - name: C
    web_url: https://github.com/topics/c
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/c/c.png
  - name: C++
    web_url: https://github.com/topics/cpp
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/cpp/cpp.png
  - name: C#
    web_url: https://github.com/topics/csharp
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/csharp/csharp.png
  - name: Linux
    web_url: https://github.com/topics/linux
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/linux/linux.png
  - name: nginx
    web_url: https://github.com/topics/nginx
  - name: libvips
    web_url: https://github.com/topics/libvips

compress_html:
  clippings: [html, head, body, link, meta, div, p, h1, h2, img, title, svg, a, span]
  comments: all
